-- MariaDB

use id18333488_site; --dont use this on 000webhost

insert into department values 
("Department of Computer Engineering","head@ce.pdn.ac.lk","http://ce.pdn.ac.lk","http://people.ce.pdn.ac.lk","https://projects.ce.pdn.ac.lk");

INSERT INTO student VALUES
('E/16/012','e16012@eng.pdn.ac.lk','','Adikari','Adikari','','','Department of Computer Engineering'),
('E/16/022','e16022@eng.pdn.ac.lk','','Amarasinghe D.L.C.','Amarasinghe D.L.C.','','','Department of Computer Engineering'),
('E/16/025','e16025@eng.pdn.ac.lk','','Amasith K.T.D.','Amasith K.T.D.','','','Department of Computer Engineering'),
('E/16/039','e16039@eng.pdn.ac.lk','','Balasuriya B.M.N.U. Ms','Balasuriya B.M.N.U. Ms','','','Department of Computer Engineering'),
('E/16/049','e16049@eng.pdn.ac.lk','','Harshana Bandara','Harshana Bandara','','','Department of Computer Engineering'),
('E/16/054','e16054@eng.pdn.ac.lk','','Basnayake S.S.','Basnayake S.S.','','','Department of Computer Engineering'),
('E/16/055','e16055@eng.pdn.ac.lk','','Bragadeeshan S.','Bragadeeshan S.','','','Department of Computer Engineering'),
('E/16/057','e16057@eng.pdn.ac.lk','','Kavindu Chamith','Kavindu Chamith','','','Department of Computer Engineering'),
('E/16/061','e16061@eng.pdn.ac.lk','Madushan Chandula','Chandula','J.P.D.M. Chandula','','','Department of Computer Engineering'),
('E/16/068','e16068@eng.pdn.ac.lk','','De Silva K.R.','De Silva K.R.','','','Department of Computer Engineering'),
('E/16/069','e16069@eng.pdn.ac.lk','','De Silva M.D.S. Ms','De Silva M.D.S. Ms','','','Department of Computer Engineering'),
('E/16/070','e16070@eng.pdn.ac.lk','Chaminie De Silva','Chaminie','N. S. C. K. S. De Silva','','','Department of Computer Engineering'),
('E/16/076','e16076@eng.pdn.ac.lk','Chamli Deshan','Deshan','L.A.C. Deshan','','','Department of Computer Engineering'),
('E/16/081','e16081@eng.pdn.ac.lk','Praveen Dhananjaya','Praveen','J.M.Praveen Dhananjaya','','','Department of Computer Engineering'),
('E/16/083','e16083@eng.pdn.ac.lk','Viraj Dhanushka','Viraj','S.M. Viraj Dhanushka','','','Department of Computer Engineering'),
('E/16/086','e16086@eng.pdn.ac.lk','','Dharmathilaka A.L.V.H. Ms','Dharmathilaka A.L.V.H. Ms','','','Department of Computer Engineering'),
('E/16/087','e16087@eng.pdn.ac.lk','','Dissanayaka W.M.S.C. Ms','Dissanayaka W.M.S.C. Ms','','','Department of Computer Engineering'),
('E/16/088','e16088@eng.pdn.ac.lk','','Dissanayake D.M.T.H.','Dissanayake D.M.T.H.','','','Department of Computer Engineering'),
('E/16/089','e16089@eng.pdn.ac.lk','Denuke Dissanayake','Denuke','N.A.D.D. Dissanayake','','','Department of Computer Engineering'),
('E/16/094','e16094@eng.pdn.ac.lk','','Shirly Madushanka','Shirly Madushanka','','','Department of Computer Engineering'),
('E/16/096','e16096@eng.pdn.ac.lk','','Ekanayake J.E.M.D.Y. Ms','Ekanayake J.E.M.D.Y. Ms','','','Department of Computer Engineering'),
('E/16/115','e16115@eng.pdn.ac.lk','','Girishikan S.','Girishikan S.','','','Department of Computer Engineering'),
('E/16/126','e16126@eng.pdn.ac.lk','','Hansika D.G.N. Ms','Hansika D.G.N. Ms','','','Department of Computer Engineering'),
('E/16/127','e16127@eng.pdn.ac.lk','','Harshana P.Y.S.','Harshana P.Y.S.','','','Department of Computer Engineering'),
('E/16/134','e16134@eng.pdn.ac.lk','','Herath H.M.Y.B.','Herath H.M.Y.B.','','','Department of Computer Engineering'),
('E/16/156','e16156@eng.pdn.ac.lk','','Jayathilaka H.A.D.T.T. Ms','Jayathilaka H.A.D.T.T. Ms','','','Department of Computer Engineering'),
('E/16/168','e16168@eng.pdn.ac.lk','','Kalpage S.W.','Kalpage S.W.','','','Department of Computer Engineering'),
('E/16/172','e16172@eng.pdn.ac.lk','','Karikaran V.','Karikaran V.','','','Department of Computer Engineering'),
('E/16/173','e16173@eng.pdn.ac.lk','','Karunarathna D.A.D.T.','Karunarathna D.A.D.T.','','','Department of Computer Engineering'),
('E/16/200','e16200@eng.pdn.ac.lk','Sumudu Liyanage','Sumudu','B. L. S. Lakmali','','','Department of Computer Engineering'),
('E/16/203','e16203@eng.pdn.ac.lk','Isuru Lakshan','Isuru','S.A.I Lakshan','','','Department of Computer Engineering'),
('E/16/217','e16217@eng.pdn.ac.lk','','Madushan K.H.G.H.','Madushan K.H.G.H.','','','Department of Computer Engineering'),
('E/16/222','e16222@eng.pdn.ac.lk','','Wishva','Wishva','','','Department of Computer Engineering'),
('E/16/223','e16223@eng.pdn.ac.lk','','Madushanki K.H.H.C. Ms','Madushanki K.H.H.C. Ms','','','Department of Computer Engineering'),
('E/16/232','e16232@eng.pdn.ac.lk','Shamra Marzook','Shamra','F.S. Marzook','','','Department of Computer Engineering'),
('E/16/242','e16242@eng.pdn.ac.lk','','A.V.S.S.A Munasinghe','A.V.S.S.A Munasinghe','','','Department of Computer Engineering'),
('E/16/261','e16261@eng.pdn.ac.lk','','Nuwantha B.L.A.','Nuwantha B.L.A.','','','Department of Computer Engineering'),
('E/16/267','e16267@eng.pdn.ac.lk','','Parackrama G.T.W. Ms','Parackrama G.T.W. Ms','','','Department of Computer Engineering'),
('E/16/275','e16275@eng.pdn.ac.lk','Hashan Eranga','Hashan','A. L. H. E Perera','','','Department of Computer Engineering'),
('E/16/276','e16276@eng.pdn.ac.lk','Buddhi Perera','Buddhi','Perera G.K.B.H.','','','Department of Computer Engineering'),
('E/16/286','e16286@eng.pdn.ac.lk','Nuwan Piyarathna','Nuwan','M.G.N.H.Piyarathna','','','Department of Computer Engineering'),
('E/16/290','e16290@eng.pdn.ac.lk','','Kalani Prabodha','Kalani Prabodha','','','Department of Computer Engineering'),
('E/16/313','e16313@eng.pdn.ac.lk','','Maneesha Randeniya','Maneesha Randeniya','','','Department of Computer Engineering'),
('E/16/319','e16319@eng.pdn.ac.lk','','Rathnayaka R.P.V.N.','Rathnayaka R.P.V.N.','','','Department of Computer Engineering'),
('E/16/320','e16320@eng.pdn.ac.lk','','Rathnayake E.W.S.P.','Rathnayake E.W.S.P.','','','Department of Computer Engineering'),
('E/16/332','e16332@eng.pdn.ac.lk','Randika Viraj','Randika','A A R V Samaraweera','','','Department of Computer Engineering'),
('E/16/351','e16351@eng.pdn.ac.lk','','Shanaka T.K.M.','Shanaka T.K.M.','','','Department of Computer Engineering'),
('E/16/360','e16360@eng.pdn.ac.lk','','Somarathna N.C.D.','Somarathna N.C.D.','','','Department of Computer Engineering'),
('E/16/364','e16364@eng.pdn.ac.lk','Tharushi Suwaris','Tharushi','T.T.N. Suwaris','','','Department of Computer Engineering'),
('E/16/366','e16366@eng.pdn.ac.lk','Dinindu Thilakarathna','Dinindu','Thilakarathna W.M.D.U.','','','Department of Computer Engineering'),
('E/16/368','e16368@eng.pdn.ac.lk','','Thisanke M.K.H.','Thisanke M.K.H.','','','Department of Computer Engineering'),
('E/16/369','e16369@eng.pdn.ac.lk','','Rusiru Thushara','Rusiru Thushara','','','Department of Computer Engineering'),
('E/16/377','e16377@eng.pdn.ac.lk','','Vindula I.B.S.','Vindula I.B.S.','','','Department of Computer Engineering'),
('E/16/388','e16388@eng.pdn.ac.lk','','Weerasundara W.M.T.M.P.B.','Weerasundara W.M.T.M.P.B.','','','Department of Computer Engineering'),
('E/16/389','e16389@eng.pdn.ac.lk','','Welikanda V.H.L.N.','Welikanda V.H.L.N.','','','Department of Computer Engineering'),
('E/16/394','e16394@eng.pdn.ac.lk','','Wijayasinghe S.D.D.D.','Wijayasinghe S.D.D.D.','','','Department of Computer Engineering'),
('E/16/396','e16396@eng.pdn.ac.lk','','Wijekoon W.M.T.S.','Wijekoon W.M.T.S.','','','Department of Computer Engineering'),
('E/16/399','e16399@eng.pdn.ac.lk','','Erandana Wijerathne','Erandana Wijerathne','','','Department of Computer Engineering'),
('E/17/004','e17004@eng.pdn.ac.lk','','Abeyweera S.K.','Abeyweera S.K.','','','Department of Computer Engineering'),
('E/17/005','e17005@eng.pdn.ac.lk','','Ahamed M.I.R.','Ahamed M.I.R.','','','Department of Computer Engineering'),
('E/17/006','e17006@eng.pdn.ac.lk','','Alahakoon A.M.H.H.','Alahakoon A.M.H.H.','','','Department of Computer Engineering'),
('E/17/008','e17008@eng.pdn.ac.lk','','Alahakoon T.','Alahakoon T.','','','Department of Computer Engineering'),
('E/17/012','e17012@eng.pdn.ac.lk','','Amarasinghe R.A.A.U.','Amarasinghe R.A.A.U.','','','Department of Computer Engineering'),
('E/17/015','e17015@eng.pdn.ac.lk','','Arshadh M.R.M.','Arshadh M.R.M.','','','Department of Computer Engineering'),
('E/17/018','e17018@eng.pdn.ac.lk','Imesh Balasuriya','Imesh','I.S. Balasuriya','','','Department of Computer Engineering'),
('E/17/024','e17024@eng.pdn.ac.lk','','Bandara K.G.K.R.','Bandara K.G.K.R.','','','Department of Computer Engineering'),
('E/17/027','e17027@eng.pdn.ac.lk','','Bandara S.M.P.C.','Bandara S.M.P.C.','','','Department of Computer Engineering'),
('E/17/035','e17035@eng.pdn.ac.lk','','Chamika K.T.M.','Chamika K.T.M.','','','Department of Computer Engineering'),
('E/17/038','e17038@eng.pdn.ac.lk','','Chandrasekara C.M.A.','Chandrasekara C.M.A.','','','Department of Computer Engineering'),
('E/17/040','e17040@eng.pdn.ac.lk','','Chandrasena M.M.D.','Chandrasena M.M.D.','','','Department of Computer Engineering'),
('E/17/044','e17044@eng.pdn.ac.lk','','Coralage D.T.S.','Coralage D.T.S.','','','Department of Computer Engineering'),
('E/17/053','e17053@eng.pdn.ac.lk','','De Silva M.G.S.C.','De Silva M.G.S.C.','','','Department of Computer Engineering'),
('E/17/058','e17058@eng.pdn.ac.lk','Isuri Devindi','Isuri','G.A.I. Devindi','','','Department of Computer Engineering'),
('E/17/064','e17064@eng.pdn.ac.lk','','Dhushintha R.','Dhushintha R.','','','Department of Computer Engineering'),
('E/17/065','e17065@eng.pdn.ac.lk','','Dilhan M.A.K.','Dilhan M.A.K.','','','Department of Computer Engineering'),
('E/17/072','e17072@eng.pdn.ac.lk','Dinura Dissanayake','Dinura','D.M.D.R. Dissanayake','','','Department of Computer Engineering'),
('E/17/083','e17083@eng.pdn.ac.lk','','Ekanayake E.M.M.U.B.','Ekanayake E.M.M.U.B.','','','Department of Computer Engineering'),
('E/17/090','e17090@eng.pdn.ac.lk','','Francis F.B.A.H.','Francis F.B.A.H.','','','Department of Computer Engineering'),
('E/17/091','e17091@eng.pdn.ac.lk','','Gallage P.G.A.P.','Gallage P.G.A.P.','','','Department of Computer Engineering'),
('E/17/100','e17100@eng.pdn.ac.lk','','Gunathilaka R.M.S.M.','Gunathilaka R.M.S.M.','','','Department of Computer Engineering'),
('E/17/101','e17101@eng.pdn.ac.lk','','Gunathilaka S.P.A.U.','Gunathilaka S.P.A.U.','','','Department of Computer Engineering'),
('E/17/122','e17122@eng.pdn.ac.lk','','Isthikar F.S.','Isthikar F.S.','','','Department of Computer Engineering'),
('E/17/134','e17134@eng.pdn.ac.lk','','Kavindu Jayasooriya','Kavindu Jayasooriya','','','Department of Computer Engineering'),
('E/17/144','e17144@eng.pdn.ac.lk','Denuka Jayaweera','Denuka','K.P.C.D.B. Jayaweera','','','Department of Computer Engineering'),
('E/17/148','e17148@eng.pdn.ac.lk','','Kalpana M.W.V.','Kalpana M.W.V.','','','Department of Computer Engineering'),
('E/17/153','e17153@eng.pdn.ac.lk','','Karunachandra R.H.I.O.','Karunachandra R.H.I.O.','','','Department of Computer Engineering'),
('E/17/154','e17154@eng.pdn.ac.lk','Akila Karunanayake','Akila','A.I. Karunanayake','','','Department of Computer Engineering'),
('E/17/156','e17156@eng.pdn.ac.lk','','Karunarathna M.G.I.U.','Karunarathna M.G.I.U.','','','Department of Computer Engineering'),
('E/17/159','e17159@eng.pdn.ac.lk','','Kavinaya Y.','Kavinaya Y.','','','Department of Computer Engineering'),
('E/17/168','e17168@eng.pdn.ac.lk','','Kodagoda K.H.S.P.','Kodagoda K.H.S.P.','','','Department of Computer Engineering'),
('E/17/176','e17176@eng.pdn.ac.lk','','Kumara W.M.E.S.K.','Kumara W.M.E.S.K.','','','Department of Computer Engineering'),
('E/17/190','e17190@eng.pdn.ac.lk','','Liyanage S.N.','Liyanage S.N.','','','Department of Computer Engineering'),
('E/17/194','e17194@eng.pdn.ac.lk','','Madhushan R.','Madhushan R.','','','Department of Computer Engineering'),
('E/17/201','e17201@eng.pdn.ac.lk','','Madushani W.T.','Madushani W.T.','','','Department of Computer Engineering'),
('E/17/206','e17206@eng.pdn.ac.lk','','Manohara H.T.','Manohara H.T.','','','Department of Computer Engineering'),
('E/17/207','e17207@eng.pdn.ac.lk','','Marasinghe M.A.P.G.','Marasinghe M.A.P.G.','','','Department of Computer Engineering'),
('E/17/212','e17212@eng.pdn.ac.lk','','Morais K.W.G.A.N.D.','Morais K.W.G.A.N.D.','','','Department of Computer Engineering'),
('E/17/219','e17219@eng.pdn.ac.lk','','Nawarathna K.G.I.S.','Nawarathna K.G.I.S.','','','Department of Computer Engineering'),
('E/17/230','e17230@eng.pdn.ac.lk','','Nishankar S.','Nishankar S.','','','Department of Computer Engineering'),
('E/17/240','e17240@eng.pdn.ac.lk','','Nadeesha Diwakara','Nadeesha Diwakara','','','Department of Computer Engineering'),
('E/17/242','e17242@eng.pdn.ac.lk','','Perera C.R.M.','Perera C.R.M.','','','Department of Computer Engineering'),
('E/17/246','e17246@eng.pdn.ac.lk','','Perera K.S.D.','Perera K.S.D.','','','Department of Computer Engineering'),
('E/17/251','e17251@eng.pdn.ac.lk','','Perera S.S.','Perera S.S.','','','Department of Computer Engineering'),
('E/17/252','e17252@eng.pdn.ac.lk','','Perera U.A.K.K.','Perera U.A.K.K.','','','Department of Computer Engineering'),
('E/17/256','e17256@eng.pdn.ac.lk','','Piriyaraj S.','Piriyaraj S.','','','Department of Computer Engineering'),
('E/17/259','e17259@eng.pdn.ac.lk','','Piyumi Bhagya S','Piyumi Bhagya S','','','Department of Computer Engineering'),
('E/17/284','e17284@eng.pdn.ac.lk','','Rathnayaka R.L.D.A.S.','Rathnayaka R.L.D.A.S.','','','Department of Computer Engineering'),
('E/17/286','e17286@eng.pdn.ac.lk','','Rathnayaka R.M.T.N.K.','Rathnayaka R.M.T.N.K.','','','Department of Computer Engineering'),
('E/17/292','e17292@eng.pdn.ac.lk','','Rilwan M.M.M.','Rilwan M.M.M.','','','Department of Computer Engineering'),
('E/17/294','e17294@eng.pdn.ac.lk','','Rossmaree D.M.','Rossmaree D.M.','','','Department of Computer Engineering'),
('E/17/296','e17296@eng.pdn.ac.lk','Ravisha Rupasinghe','Ravisha','R.H. Rupasinghe','','','Department of Computer Engineering'),
('E/17/297','e17297@eng.pdn.ac.lk','Vishva Navanjana','Vishva','T.T.V.N. Rupasinghe','','','Department of Computer Engineering'),
('E/17/312','e17312@eng.pdn.ac.lk','','Sangarasekara S.A.I.U.','Sangarasekara S.A.I.U.','','','Department of Computer Engineering'),
('E/17/318','e17318@eng.pdn.ac.lk','','Udith Senanayake','Udith Senanayake','','','Department of Computer Engineering'),
('E/17/327','e17327@eng.pdn.ac.lk','','Shalha A.M.F.','Shalha A.M.F.','','','Department of Computer Engineering'),
('E/17/331','e17331@eng.pdn.ac.lk','Sathira Silva','Sathira','H.S.C. Silva','','','Department of Computer Engineering'),
('E/17/338','e17338@eng.pdn.ac.lk','','Srimal R.M.L.C.','Srimal R.M.L.C.','','','Department of Computer Engineering'),
('E/17/342','e17342@eng.pdn.ac.lk','','Mr. Tharmapalan Thanujan','Mr. Tharmapalan Thanujan','','','Department of Computer Engineering'),
('E/17/352','e17352@eng.pdn.ac.lk','','Isara Tillekeratne','Isara Tillekeratne','','','Department of Computer Engineering'),
('E/17/358','e17358@eng.pdn.ac.lk','Varnaraj','Varnaa','N.Varnaraj','','','Department of Computer Engineering'),
('E/17/369','e17369@eng.pdn.ac.lk','','Wannigama S.B.','Wannigama S.B.','','','Department of Computer Engineering'),
('E/17/379','e17379@eng.pdn.ac.lk','','Weerasinghe S.P.D.D.S.','Weerasinghe S.P.D.D.S.','','','Department of Computer Engineering'),
('E/17/380','e17380@eng.pdn.ac.lk','Shamal Weerasooriya','Shamal','Weerasooriya S.S.','','','Department of Computer Engineering'),
('E/17/388','e17388@eng.pdn.ac.lk','','Weragoda W.A.L.M.','Weragoda W.A.L.M.','','','Department of Computer Engineering'),
('E/17/398','e17398@eng.pdn.ac.lk','','Wijerathne I.D.H.S.D.','Wijerathne I.D.H.S.D.','','','Department of Computer Engineering'),
('E/17/405','e17405@eng.pdn.ac.lk','','Wijesinghe W.D.L.P.','Wijesinghe W.D.L.P.','','','Department of Computer Engineering'),
('E/17/407','e17407@eng.pdn.ac.lk','Hasara Wijesooriya','Hasara','H.D Wijesooriya','','','Department of Computer Engineering'),
('E/18/009','e18009@eng.pdn.ac.lk','','Abeyweera P.S.','Abeyweera P.S.','','','Department of Computer Engineering'),
('E/18/010','e18010@eng.pdn.ac.lk','','Abeywickrama A.K.D.A.S.','Abeywickrama A.K.D.A.S.','','','Department of Computer Engineering'),
('E/18/013','e18013@eng.pdn.ac.lk','','Abilash R.','Abilash R.','','','Department of Computer Engineering'),
('E/18/014','e18014@eng.pdn.ac.lk','','Ahamad I.L.A.','Ahamad I.L.A.','','','Department of Computer Engineering'),
('E/18/017','e18017@eng.pdn.ac.lk','','Aarah J.F.','Aarah J.F.','','','Department of Computer Engineering'),
('E/18/022','e18022@eng.pdn.ac.lk','','Amarasinghe D.I.','Amarasinghe D.I.','','','Department of Computer Engineering'),
('E/18/028','e18028@eng.pdn.ac.lk','','Ariyawansha P.H.J.U.','Ariyawansha P.H.J.U.','','','Department of Computer Engineering'),
('E/18/030','e18030@eng.pdn.ac.lk','','Aththanayaka A.M.S.','Aththanayaka A.M.S.','','','Department of Computer Engineering'),
('E/18/036','e18036@eng.pdn.ac.lk','','Bandara L.R.M.U.','Bandara L.R.M.U.','','','Department of Computer Engineering'),
('E/18/058','e18058@eng.pdn.ac.lk','','De Alwis K.K.M.','De Alwis K.K.M.','','','Department of Computer Engineering'),
('E/18/063','e18063@eng.pdn.ac.lk','','Dedigamuwa N.T.','Dedigamuwa N.T.','','','Department of Computer Engineering'),
('E/18/068','e18068@eng.pdn.ac.lk','','Devinda G.C.','Devinda G.C.','','','Department of Computer Engineering'),
('E/18/073','e18073@eng.pdn.ac.lk','','Dhananjaya W.M.T.','Dhananjaya W.M.T.','','','Department of Computer Engineering'),
('E/18/077','e18077@eng.pdn.ac.lk','','Dharmarathne N.S.','Dharmarathne N.S.','','','Department of Computer Engineering'),
('E/18/097','e18097@eng.pdn.ac.lk','','Eswaran M.','Eswaran M.','','','Department of Computer Engineering'),
('E/18/098','e18098@eng.pdn.ac.lk','Ishan Fernando','Ishan','K.A.I. Fernando','','','Department of Computer Engineering'),
('E/18/100','e18100@eng.pdn.ac.lk','Adeepa Fernando','Adeepa','Fernando K.N.A.','','','Department of Computer Engineering'),
('E/18/115','e18115@eng.pdn.ac.lk','','Gowsigan A.','Gowsigan A.','','','Department of Computer Engineering'),
('E/18/118','e18118@eng.pdn.ac.lk','','Gunarathna H.P.H.M.','Gunarathna H.P.H.M.','','','Department of Computer Engineering'),
('E/18/126','e18126@eng.pdn.ac.lk','','Gurusinghe D.C.','Gurusinghe D.C.','','','Department of Computer Engineering'),
('E/18/128','e18128@eng.pdn.ac.lk','','Hariharan R.','Hariharan R.','','','Department of Computer Engineering'),
('E/18/131','e18131@eng.pdn.ac.lk','','Hemachandra K.T.H.','Hemachandra K.T.H.','','','Department of Computer Engineering'),
('E/18/147','e18147@eng.pdn.ac.lk','Saadia Jameel','Saadia','S. Jameel','','','Department of Computer Engineering'),
('E/18/149','e18149@eng.pdn.ac.lk','','Jayakody J.M.I.H.','Jayakody J.M.I.H.','','','Department of Computer Engineering'),
('E/18/150','e18150@eng.pdn.ac.lk','','Jayarathna H.M.Y.S.','Jayarathna H.M.Y.S.','','','Department of Computer Engineering'),
('E/18/154','e18154@eng.pdn.ac.lk','','Jayasumana C.H.','Jayasumana C.H.','','','Department of Computer Engineering'),
('E/18/155','e18155@eng.pdn.ac.lk','','Jayasundara J.W.K.R.B.','Jayasundara J.W.K.R.B.','','','Department of Computer Engineering'),
('E/18/156','e18156@eng.pdn.ac.lk','','Jayathilake W.A.T.N.','Jayathilake W.A.T.N.','','','Department of Computer Engineering'),
('E/18/168','e18168@eng.pdn.ac.lk','','Karan R.','Karan R.','','','Department of Computer Engineering'),
('E/18/170','e18170@eng.pdn.ac.lk','','Karunarathna W.K.','Karunarathna W.K.','','','Department of Computer Engineering'),
('E/18/173','e18173@eng.pdn.ac.lk','','Kasthuripitiya K.A.I.M.','Kasthuripitiya K.A.I.M.','','','Department of Computer Engineering'),
('E/18/177','e18177@eng.pdn.ac.lk','','Khan A.K.M.S.','Khan A.K.M.S.','','','Department of Computer Engineering'),
('E/18/178','e18178@eng.pdn.ac.lk','','Kithmal P.G.S.','Kithmal P.G.S.','','','Department of Computer Engineering'),
('E/18/180','e18180@eng.pdn.ac.lk','','Kodituwakku M.K.N.M.','Kodituwakku M.K.N.M.','','','Department of Computer Engineering'),
('E/18/181','e18181@eng.pdn.ac.lk','','Konara K.M.S.L.','Konara K.M.S.L.','','','Department of Computer Engineering'),
('E/18/203','e18203@eng.pdn.ac.lk','','Madhusanka K.G.A.S.','Madhusanka K.G.A.S.','','','Department of Computer Engineering'),
('E/18/214','e18214@eng.pdn.ac.lk','Kushan Manahara','Kushan','H.K. Manahara','','','Department of Computer Engineering'),
('E/18/224','e18224@eng.pdn.ac.lk','','Mihiranga G.D.R.','Mihiranga G.D.R.','','','Department of Computer Engineering'),
('E/18/227','e18227@eng.pdn.ac.lk','','Mudalige D.H.','Mudalige D.H.','','','Department of Computer Engineering'),
('E/18/230','e18230@eng.pdn.ac.lk','','Munathanthri M.D.H.I.','Munathanthri M.D.H.I.','','','Department of Computer Engineering'),
('E/18/242','e18242@eng.pdn.ac.lk','','Nimnadi J.A.S.','Nimnadi J.A.S.','','','Department of Computer Engineering'),
('E/18/245','e18245@eng.pdn.ac.lk','','Nishani K.','Nishani K.','','','Department of Computer Engineering'),
('E/18/264','e18264@eng.pdn.ac.lk','','Prasanna N.W.G.L.M.','Prasanna N.W.G.L.M.','','','Department of Computer Engineering'),
('E/18/266','e18266@eng.pdn.ac.lk','','Premathilaka K.N.I.','Premathilaka K.N.I.','','','Department of Computer Engineering'),
('E/18/276','e18276@eng.pdn.ac.lk','','Rajasooriya J.M.','Rajasooriya J.M.','','','Department of Computer Engineering'),
('E/18/282','e18282@eng.pdn.ac.lk','Nethmi Sudeni','Nethmi','Ranasinghe R.A.N.S.','','','Department of Computer Engineering'),
('E/18/283','e18283@eng.pdn.ac.lk','','Ranasinghe R.D.J.M.','Ranasinghe R.D.J.M.','','','Department of Computer Engineering'),
('E/18/285','e18285@eng.pdn.ac.lk','','Ranasinghe S.M.T.S.C.','Ranasinghe S.M.T.S.C.','','','Department of Computer Engineering'),
('E/18/297','e18297@eng.pdn.ac.lk','','Rathnayake R.M.P.P.','Rathnayake R.M.P.P.','','','Department of Computer Engineering'),
('E/18/304','e18304@eng.pdn.ac.lk','','Rishad N.M.','Rishad N.M.','','','Department of Computer Engineering'),
('E/18/316','e18316@eng.pdn.ac.lk','','Sandaruwan V.B.','Sandaruwan V.B.','','','Department of Computer Engineering'),
('E/18/318','e18318@eng.pdn.ac.lk','','Sandunika S.A.P.','Sandunika S.A.P.','','','Department of Computer Engineering'),
('E/18/323','e18323@eng.pdn.ac.lk','','Seekkubadu H.D.','Seekkubadu H.D.','','','Department of Computer Engineering'),
('E/18/327','e18327@eng.pdn.ac.lk','','Senevirathna M.D.C.D.','Senevirathna M.D.C.D.','','','Department of Computer Engineering'),
('E/18/329','e18329@eng.pdn.ac.lk','','Sewwandi D.W.S.N.','Sewwandi D.W.S.N.','','','Department of Computer Engineering'),
('E/18/330','e18330@eng.pdn.ac.lk','','Sewwandi H.R.','Sewwandi H.R.','','','Department of Computer Engineering'),
('E/18/340','e18340@eng.pdn.ac.lk','','Subramanieam V.','Subramanieam V.','','','Department of Computer Engineering'),
('E/18/349','e18349@eng.pdn.ac.lk','','Thalisha W.G.A.P.','Thalisha W.G.A.P.','','','Department of Computer Engineering'),
('E/18/354','e18354@eng.pdn.ac.lk','','Tharaka K.K.D.R.','Tharaka K.K.D.R.','','','Department of Computer Engineering'),
('E/18/366','e18366@eng.pdn.ac.lk','','Thulasiyan Y.','Thulasiyan Y.','','','Department of Computer Engineering'),
('E/18/368','e18368@eng.pdn.ac.lk','','Uduwanage H.U.','Uduwanage H.U.','','','Department of Computer Engineering'),
('E/18/373','e18373@eng.pdn.ac.lk','','Vilakshan V.','Vilakshan V.','','','Department of Computer Engineering'),
('E/18/375','e18375@eng.pdn.ac.lk','','Vindula K.P.A.','Vindula K.P.A.','','','Department of Computer Engineering'),
('E/18/379','e18379@eng.pdn.ac.lk','Thamish Wanduragala','Thamish','T.D.B. Wanduragala','','','Department of Computer Engineering'),
('E/18/382','e18382@eng.pdn.ac.lk','','Weerarathne L.D.','Weerarathne L.D.','','','Department of Computer Engineering'),
('E/18/397','e18397@eng.pdn.ac.lk','','Wijerathne E.S.G.','Wijerathne E.S.G.','','','Department of Computer Engineering'),
('E/18/398','e18398@eng.pdn.ac.lk','','Wijerathne R.M.N.S.','Wijerathne R.M.N.S.','','','Department of Computer Engineering'),
('E/18/402','e18402@eng.pdn.ac.lk','','Wimalasiri K.H.C.T.','Wimalasiri K.H.C.T.','','','Department of Computer Engineering'),
('E/18/406','e18406@eng.pdn.ac.lk','','Zameer M.H.M.','Zameer M.H.M.','','','Department of Computer Engineering'),
('E/18/412','e18412@eng.pdn.ac.lk','','De Silva M.S.G.M.','De Silva M.S.G.M.','','','Department of Computer Engineering');

insert into company values
(1,"company1","first@company.com",'someRank','https://google.com','We are google','addressline1','addressline2','country','state');

insert into company_awards values 
(1,"Worlds worst company award for 2022");

insert into company_services values 
(1,"Google search engine"),
(1,"Gmail"),
(1,"Google Cloud Platform");

insert into supervisor values
(1,"supervisorName1",'supervisor@compnay1.com','077123456789',1);

insert into supervises values 
(1,"E/18/098");

insert into instructor values
(1,"instructor1",'instructor1@ce.pdn.ac.lk','07987654321','Department of Computer Engineering');

insert into instructs values 
(1,"E/18/098");

insert into lecturer values
(1,'lecturer1','lecturer@ce.pdn.ac.lk','0123123465789','Department of Computer Engineering');

insert into guides values 
(1, "E/18/098");

insert into internship values
(1,1,"2 months","Online","Software developing","$50000");

insert into requests values
(1,'E/18/098',"2022/02/12");

insert into student_works_in values 
("E/18/155",1);

insert into student_skills values
("E/18/155","Python"),
("E/18/155","C"),
("E/18/155","PHP"),
("E/18/155","Verilog"),
("E/18/155","MySQL");